collections:
  cc:
    output: true
  portfolio:
    output: true


defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"  
  - scope:
      path: ""
      type: "cc"
    values:
      layout: "code"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
