collections:
  codes:
    output: true
  portfolio:
    output: true


defaults:
  - scope:
      path: ""
      type: "coding"
    values:
      layout: "code"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
